### ISSUE TITLE
Build failure under Arch Linux, GCC 12.1 

### ISSUE THREAD

**Issue by stefanhusmann** [blippy/neoleo#48]
Using gcc the compilation fails. With clang it works fine.
 ```
==> Making package: neoleo-git 12.0-1 (Tue Jul 12 12:25:20 2022)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating neoleo git repo...
==> Validating source files with sha256sums...
    neoleo ... Skipped
==> Extracting sources...
  -> Creating working copy of neoleo git repo...
Reset branch 'makepkg'
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
autoreconf: Leaving directory '.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
configure: checking if debugging required ... no
configure: checking if gprof profiling required ... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating examples/Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating tests/out/Makefile
config.status: creating tests/verified/Makefile
config.status: executing depfiles commands
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
make[1]: Entering directory '/home/haawda/paketierung/meine_Pakete/neoleo-git/src/neoleo'
Making all in examples
make[2]: Entering directory '/home/haawda/paketierung/meine_Pakete/neoleo-git/src/neoleo/examples'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/haawda/paketierung/meine_Pakete/neoleo-git/src/neoleo/examples'
Making all in src
make[2]: Entering directory '/home/haawda/paketierung/meine_Pakete/neoleo-git/src/neoleo/src'
g++ -DHAVE_CONFIG_H -I. -I..    -Werror -std=c++17 -DDATADIR="\"/usr/share\"" -Wall -Wfatal-errors -Wno-psabi -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions 	-Wp,-D_FORTIFY_SOURCE=2,-Wformat -Werror=format-security 	-fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -MT oleofile.o -MD -MP -MF .deps/oleofile.Tpo -c -o oleofile.o oleofile.cc
In file included from /usr/include/c++/12.1.0/string:53,
                 from /usr/include/c++/12.1.0/bits/locale_classes.h:40,
                 from /usr/include/c++/12.1.0/bits/ios_base.h:41,
                 from /usr/include/c++/12.1.0/ios:42,
                 from /usr/include/c++/12.1.0/ostream:38,
                 from /usr/include/c++/12.1.0/iostream:39,
                 from oleofile.cc:25:
In constructor 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with <template-parameter-2-1> = std::allocator<char>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]',
    inlined from 'char* read_new_value(CELLREF, CELLREF, char*, char*)' at oleofile.cc:54:16:
/usr/include/c++/12.1.0/bits/basic_string.h:641:23: error: 'text' may be used uninitialized [-Werror=maybe-uninitialized]
  641 |         const _CharT* __end = __s + traits_type::length(__s);
      |                       ^~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:481: oleofile.o] Error 1
make[2]: Leaving directory '/home/haawda/paketierung/meine_Pakete/neoleo-git/src/neoleo/src'
make[1]: *** [Makefile:416: all-recursive] Error 1
make[1]: Leaving directory '/home/haawda/paketierung/meine_Pakete/neoleo-git/src/neoleo'
make: *** [Makefile:336: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

Process makepkg exited abnormally with code 4
```

**Comment by blippy** [comment]
I have tried the default g++ compiler on Debian Stable, and neoleo builds fine. I installed v 12.1.0 on Debian, and still get a clean build. I think that Arch adds in some extra restrictions under the hood, but I don't know what they are.  It's going to be tricky to resolve.

**Comment by blippy** [comment]
I have been able to identify the flags that are causing the build failure. I am now in a position to investigate the problem further. Stay tuned.

**Comment by blippy** [comment]
Adding the -O2 flag seems to be integral to producing the compile error. Hmmm. Is this a compiler bug, perhaps, in addition to whatever problem my code might have?

**Comment by blippy** [comment]
It seems to compile OK with g++ v10.2.1, but 12.1.0 doesn't like it.

**Comment by blippy** [comment]
Try the new release  v12.1. Please confirm if it compiles, or not.

**Comment by stefanhusmann** [comment]
Hello, 
thanks for looking at this.
For me it still does not build, but the error message is different.
```
make[2]: Entering directory '/home/haawda/paketierung/meine_Pakete/neoleo/src/neoleo-12.1/src'
g++ -DHAVE_CONFIG_H -I. -I..    -Werror -std=c++17 -DDATADIR="\"/usr/share\"" -Wuninitialized -Wfatal-errors -Wno-psabi -Wall -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions 	-Wp,-D_FORTIFY_SOURCE=2,-Wformat -Werror=format-security 	-fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -MT utils.o -MD -MP -MF .deps/utils.Tpo -c -o utils.o utils.cc
utils.cc: In function 'void ck_fclose(FILE*)':
utils.cc:227:23: error: pointer 'stream' may be used after 'int fclose(FILE*)' [-Werror=use-after-free]
  227 |                 panic ("Couldn't close %s", __fp_name (stream));
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:478: utils.o] Error 1
make[2]: Leaving directory '/home/haawda/paketierung/meine_Pakete/neoleo/src/neoleo-12.1/src'
make[1]: *** [Makefile:416: all-recursive] Error 1
make[1]: Leaving directory '/home/haawda/paketierung/meine_Pakete/neoleo/src/neoleo-12.1'
make: *** [Makefile:336: all] Error 2
```

**Comment by blippy** [comment]
Hmm, I couldn't reproduce the build failure. The failure does make sense, though. I have removed the function, as it isn't called. 

Can I ask that you try to build the latest commit from source (76082a90ce5a945227c2d00d880814c91ca544c2)
and tell me if you get a successful compile.

There's obviously some extra compilation strictness that Arch has that Debian doesn't. It makes it difficult for me ferret out all the potential problem. 

It may help to do
```
source /etc/makepkg.conf
```
beforehand, because I think it sets some flags that may be causing the problem I thought that I had sorted the problem out, but obviously not.

**Comment by stefanhusmann** [comment]
g76082a9 builds fine.

[makepkg.txt](https://github.com/blippy/neoleo/files/9113185/makepkg.txt)

**Comment by blippy** [comment]
I pushed a new release. Hopefully this will now work for you. Please advise.

**Comment by stefanhusmann** [comment]
Works fine, thanks.

**Comment by blippy** [comment]
Cool beans. Thanks for your interest. I'll close the issue.

Hopefully Arch won't introduce any other compilation flags that cause problems.
